/**
 * DO NOT EDIT THIS FILE
 * THOSE ARE JUST HELPER FUNCTIONS FOR SEASON 3
 */

const args = process.argv.slice(2);
const level = args[0];
const guess = args[1];
const secret = process.env[`SEASON_3_LEVEL_${level}_SECRET`];

if (!level || !guess) {
    console.log("Please provide a level and a guess");
    process.exit(1);
}

if (guess !== secret) {
    console.log(`Sorry, your guess for Level-${level} is incorrect. Try again!`);
    process.exit(1);
}

console.log(`Congratulations! You've successfully guessed the secret for Level-${level}!`);


