// ⚠️ Do not edit — this file simulates a managed AI agent. In the real world, agents are configured by your organisation and you would not modify their code directly.
/*
 * +-----------------------------------------------------+
 * |  Docs Agent                                         |
 * |  Automated documentation generation                 |
 * +-----------------------------------------------------+
 * |  * Internal agent  |  v1.0.0                        |
 * |  Generates documentation from project files,        |
 * |  updates READMEs, and creates API references.       |
 * |  Scoped to the sandbox directory only.              |
 * |                                                     |
 * |  Features:                                          |
 * |  - Generate README from project structure           |
 * |  - Create API documentation stubs                   |
 * |  - Summarise recent changes for release notes       |
 * |                                                     |
 * |  Permissions: Sandbox read/write access             |
 * +-----------------------------------------------------+
 */

import fs from "node:fs";
import path from "node:path";

// Sandbox directory for documentation generation.
const SANDBOX = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..", "prodbot-activities");

// Agent metadata — shown by ProdBot's "agents" and "agent <name>" commands.
export const name = "Docs Agent";
export const description = "Generates documentation from project structure and code";
export const permissions = "Sandbox read/write access";
export const sourceFile = "Level-5/agents/docs-agent.js";

export const tools = {
    /** Generates a README.md from the sandbox file structure. */
    generate: {
        description: "Generate a README.md from the sandbox contents",
        usage: "generate [style]",
        run(style) {
            if (!fs.existsSync(SANDBOX)) return { error: "Sandbox not available." };
            const files = fs.readdirSync(SANDBOX).filter(f => !f.startsWith("."));
            if (files.length === 0) {
                return { result: "No files in sandbox to document. Create some files first!\n\nTry: \"Create a file called app.js with a hello world server\"" };
            }
            const fileList = files.map(f => {
                const stat = fs.statSync(path.join(SANDBOX, f));
                return `- \`${f}\` (${stat.isDirectory() ? "directory" : `${stat.size} bytes`})`;
            });
            const readme = `# Project Documentation\n\nAuto-generated by Docs Agent.\n\n## Files\n\n${fileList.join("\n")}\n\n## Getting Started\n\nTODO: Add setup instructions.\n`;
            const outPath = path.join(SANDBOX, "README.md");
            fs.writeFileSync(outPath, readme, "utf-8");
            return { result: `Generated README.md in sandbox (${files.length} files documented).\nView with: cat prodbot-activities/README.md` };
        }
    },

    /** Summarises sandbox contents for release notes. */
    summarise: {
        description: "Summarise sandbox contents for release notes",
        usage: "summarise",
        run() {
            if (!fs.existsSync(SANDBOX)) return { error: "Sandbox not available." };
            const files = fs.readdirSync(SANDBOX).filter(f => !f.startsWith("."));
            if (files.length === 0) return { result: "No files to summarise." };
            const summary = files.map(f => {
                const full = path.join(SANDBOX, f);
                const stat = fs.statSync(full);
                if (stat.isDirectory()) return `  📁 ${f}/ — directory`;
                const content = fs.readFileSync(full, "utf-8");
                const lines = content.split("\n").length;
                return `  📄 ${f} — ${lines} lines, ${stat.size} bytes`;
            });
            return { result: `Project summary (${files.length} items):\n\n${summary.join("\n")}` };
        }
    }
};
